"""initial

Revision ID: 34ab6c20340c
Revises: 
Create Date: 2026-04-28 20:19:40.689283
"""
from alembic import op
import sqlalchemy as sa


revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_entry_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('sldl_match_path', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.ForeignKeyConstraint(['track_entry_id'], ['track_entry.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('account_label', sa.String(length=128), nullable=False),
    sa.Column('access_token_enc', sa.LargeBinary(), nullable=False),
    sa.Column('refresh_token_enc', sa.LargeBinary(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scopes', sa.Text(), nullable=False),
    sa.Column('remote_user_id', sa.String(length=128), nullable=True),
    sa.Column('remote_display', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('setting',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('track_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_list_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('artist', sa.String(length=512), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('album', sa.String(length=512), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('isrc', sa.String(length=32), nullable=True),
    sa.Column('spotify_track_id', sa.String(length=64), nullable=True),
    sa.Column('yt_timestamp_sec', sa.Integer(), nullable=True),
    sa.Column('recognition_confidence', sa.Float(), nullable=True),
    sa.Column('download_status', sa.String(length=16), nullable=False),
    sa.Column('download_id', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['download_id'], ['download.id'], ),
    sa.ForeignKeyConstraint(['source_list_id'], ['source_list.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_list_id', 'isrc', name='uq_track_list_isrc')
    )
    op.create_index('ix_track_entry_list_position', 'track_entry', ['source_list_id', 'position'], unique=False)
    op.create_table('source_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('download_path', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sync_interval', sa.String(length=64), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_status', sa.String(length=16), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('oauth_account_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['oauth_account_id'], ['oauth_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('source_list_id', sa.Integer(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('log_path', sa.Text(), nullable=True),
    sa.Column('progress_json', sa.JSON(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['source_list_id'], ['source_list.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_state_sched_pri', 'job', ['state', 'scheduled_for', 'priority'], unique=False)
    op.create_table('library_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('mtime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('artist', sa.String(length=512), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.Column('album', sa.String(length=512), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('acoustid_fp', sa.Text(), nullable=True),
    sa.Column('source_list_id', sa.Integer(), nullable=True),
    sa.Column('matched_track_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['matched_track_id'], ['track_entry.id'], ),
    sa.ForeignKeyConstraint(['source_list_id'], ['source_list.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('library_file')
    op.drop_index('ix_job_state_sched_pri', table_name='job')
    op.drop_table('job')
    op.drop_table('source_list')
    op.drop_index('ix_track_entry_list_position', table_name='track_entry')
    op.drop_table('track_entry')
    op.drop_table('setting')
    op.drop_table('oauth_account')
    op.drop_table('download')
    # ### end Alembic commands ###
