# Docker Compose configuration for ToolCrate production deployment
# Self-contained deployment without local filesystem dependencies

services:
  toolcrate:
    build:
      context: .
      dockerfile: Dockerfile
    image: toolcrate:latest
    container_name: toolcrate-app
    restart: unless-stopped
    environment:
      - PYTHONPATH=/app/src
      - PYTHONUNBUFFERED=1
    working_dir: /app
    networks:
      - toolcrate-network
    # Persistent volumes for data that should survive container restarts
    volumes:
      - toolcrate-data:/app/data
      - toolcrate-logs:/app/logs
      - toolcrate-config:/app/config
      # Docker-in-Docker support for slsk-batchdl containers
      - /var/run/docker.sock:/var/run/docker.sock
    # Keep container running with a long-running command
    command: ["tail", "-f", "/dev/null"]
    # Enable Docker access with root permissions (required for macOS Docker Desktop)
    # user: "501:20"

networks:
  toolcrate-network:
    driver: bridge

volumes:
  toolcrate-data:
    driver: local
  toolcrate-logs:
    driver: local
  toolcrate-config:
    driver: local
