name: Build and Push Docker Production Image

on:
  push:
    branches: [ main, augment-feature-dev ]
    paths:
      - 'Dockerfile'
      - 'pyproject.toml'
      - 'poetry.lock'
      - 'src/**'
      - '.github/workflows/docker-build.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - 'pyproject.toml'
      - 'poetry.lock'
      - 'src/**'
      - '.github/workflows/docker-build.yml'
  workflow_dispatch:  # Allow manual triggering
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/toolcrate

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64,linux/arm64

    - name: Test the built image
      run: |
        echo "Testing the built Docker image..."
        echo "Available tags: ${{ steps.meta.outputs.tags }}"

        # Extract the first tag from the metadata output for testing
        FIRST_TAG=$(echo "${{ steps.meta.outputs.tags }}" | head -n1)
        echo "Testing with tag: $FIRST_TAG"

        # Pull the image for the current platform (linux/amd64)
        docker pull --platform linux/amd64 "$FIRST_TAG"

        # Test the image
        docker run --rm --platform linux/amd64 "$FIRST_TAG" \
          bash -c "toolcrate --version && python -c 'import toolcrate; print(\"ToolCrate imported successfully\")'"

  update-docker-compose:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/augment-feature-dev'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        submodules: recursive

    - name: Update docker-compose.yml to use registry image
      run: |
        # Update docker-compose.yml to use the registry image instead of building locally
        sed -i 's|build:|# build:|g' docker-compose.yml
        sed -i 's|context: \.|# context: \.|g' docker-compose.yml
        sed -i 's|dockerfile: Dockerfile|# dockerfile: Dockerfile|g' docker-compose.yml
        sed -i "s|image: toolcrate:latest|image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}|g" docker-compose.yml

        echo "Updated docker-compose.yml:"
        cat docker-compose.yml

    - name: Commit updated docker-compose.yml
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docker-compose.yml
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update docker-compose.yml to use registry image [skip ci]"
          git push
        fi
